{% set name = "delta" %}
{% set version = "2.0b3" %}

package:
  name: {{ name|lower }}2
  version: {{ version }}

source:
  url: https://gitlab.com/dunloplab/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e29eda6c5567569c9f04d724bdf2f712357864d8d93924a926a52eb4f86aa52b 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - python >=3.6
    - pip
    - xorg-libxfixes  # [linux]
  run:
    - python >=3.6
    - numpy >=1.20 
    - scikit-image >=0.18
    - tifffile >=2020
    - opencv >=4.1
    - tensorflow >=2
    - ffmpeg-python
    - requests

test:
  imports:
    - delta

about:
  home: https://gitlab.com/dunloplab/delta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'DeLTA (Deep Learning for Time-lapse Analysis) is a deep learning-based image processing pipeline for segmenting and tracking single cells in time-lapse microscopy movies'
  description: |
    DeLTA can process movies of rod-shaped bacteria growing in 2D setups such as
    agarose pads, as well as movies of E. coli cells trapped in a microfluidic
    device known as a mother machine. The pipeline is centered around two U-Net
    neural networks that are used for binary segmnetation and tracking cells
    frame to frame.
  dev_url: https://gitlab.com/dunloplab/delta

extra:
  recipe-maintainers:
    - jblugagne
    - owen24819
