{% set name = "delta" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}2
  version: {{ version }}

source:
  url: https://gitlab.com/dunloplab/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b60de555b88c828a95220ae55f11821e12043fb76f71a7ae4c1003965a2b362c 

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.20 
    - scikit-image >=0.18
    - tifffile >=2020
    - opencv >=4.1
    - tensorflow >=2
    - ffmpeg-python
    - requests

test:
  imports:
    - delta

about:
  home: https://gitlab.com/dunloplab/delta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'DeLTA (Deep Learning for Time-lapse Analysis) is a deep learning-based image processing pipeline for segmenting and tracking single cells in time-lapse microscopy movies'
  description: |
    DeLTA can process movies of rod-shaped bacteria growing in 2D setups such as
    agarose pads, as well as movies of E. coli cells trapped in a microfluidic
    device known as a mother machine. The pipeline is centered around two U-Net
    neural networks that are used for binary segmnetation and tracking cells
    frame to frame.
  dev_url: https://gitlab.com/dunloplab/delta

extra:
  recipe-maintainers:
    - jblugagne
    - owen24819
